const simplifiedSectorData = {
  sectors: {
    energy: {
      sector_name: 'Energy Sector',
      stocks: [
        'XOM',
        'CVX',
        'COP',
        'SLB',
        'KMI',
        'OKE',
        'MPC',
        'VLO',
        'EPD',
        'WMB',
        'HAL',
        'EOG',
      ],
    },
    materials: {
      sector_name: 'Materials Sector',
      stocks: [
        'LIN',
        'FCX',
        'APD',
        'SHW',
        'ECL',
        'BHP',
        'RIO',
        'NUE',
        'VALE',
        'CRH',
      ],
    },
    industrials: {
      sector_name: 'Industrials Sector',
      stocks: [
        'BA',
        'CAT',
        'GE',
        'MMM',
        'HON',
        'RTX',
        'UNP',
        'DE',
        'LMT',
        'WM',
      ],
    },
    utilities: {
      sector_name: 'Utilities Sector',
      stocks: [
        'NEE',
        'AEP',
        'DUK',
        'SO',
        'EXC',
        'CEG',
        'VST',
        'XEL',
        'ED',
        'WEC',
      ],
    },
    healthcare: {
      sector_name: 'Healthcare Sector',
      stocks: [
        'JNJ',
        'UNH',
        'PFE',
        'MRK',
        'ABBV',
        'TMO',
        'ABT',
        'DHR',
        'LLY',
        'AMGN',
      ],
    },
    financial: {
      sector_name: 'Financial Sector',
      stocks: [
        'GS',
        'MS',
        'C',
        'USB',
        'PNC',
        'TFC',
        'COF',
        'JPM',
        'BAC',
        'WFC',
      ],
    },
    consumer_discretionary: {
      sector_name: 'Consumer Discretionary Sector',
      stocks: [
        'AMZN',
        'TSLA',
        'HD',
        'CMG',
        'F',
        'TM',
        'MCD',
        'DIS',
        'BKNG',
        'TJX',
      ],
    },
    consumer_staples: {
      sector_name: 'Consumer Staples Sector',
      stocks: [
        'PG',
        'KO',
        'COST',
        'PEP',
        'WMT',
        'KHC',
        'PM',
        'UL',
        'BUD',
        'CL',
      ],
    },
    information_technology: {
      sector_name: 'Information Technology Sector',
      stocks: [
        'AAPL',
        'MSFT',
        'NVDA',
        'META',
        'ORCL',
        'AVGO',
        'CRM',
        'ADBE',
        'CSCO',
        'AMD',
      ],
    },
    communication_services: {
      sector_name: 'Communication Services Sector',
      stocks: [
        'DIS',
        'CMCSA',
        'VZ',
        'TMUS',
        'NFLX',
        'GOOGL',
        'WBD',
        'UBER',
        'SNAP',
        'T',
      ],
    },
    real_estate: {
      sector_name: 'Real Estate Sector',
      stocks: [
        'AMT',
        'EQIX',
        'CCI',
        'PSA',
        'SPG',
        'O',
        'WELL',
        'AVB',
        'VTR',
        'REG',
      ],
    },
  },
};

export default simplifiedSectorData;
